version: '3.8'

services:
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: abc12345
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: abc12345
    links:
      - mongo
    networks:
      - clean-node-api-network

  mongo:
    image: mongo:5.0.4
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: abc12345
    ports:
      - "27017:27017"
    volumes:
      - clean-node-api-data:/data/db
    networks:
      - clean-node-api-network

networks: 
  clean-node-api-network:
    driver: bridge

volumes:
  clean-node-api-data: